export const colorRequiredKeys = [
  "colorName",
  "hex",
  "title",
  "imageColor",
] as const;

export const requiredMainKeys = [
  "id",
  "garment",
  "name",
  "image",
  "style",
  "weather",
  "colors",
] as const;

export const garmentsKeys = ["top", "coat", "pants", "shoes", "belt"] as const;
export const styleKeys = ["basic", "casual", "elegant"] as const;
export const weatherKeys = ["cold", "mild", "hot"] as const;

export const colorNameKeys = [
  "default",
  "purple",
  "lilac",
  "aero",
  "navy",
  "frenchBlue",
  "skyBlue",
  "aquamarine",
  "emerald",
  "army",
  "yellow",
  "mustard",
  "orange",
  "windsorTan",
  "chocolate",
  "camel",
  "beige",
  "white",
  "lightGrey",
  "darkGrey",
  "black",
  "burgundy",
  "red",
  "babyPink",
  "oldPink",
  "salmon",
  "wornBlack",
  "jean",
] as const;

export const hexColorKeys = [
  "#5f2f82",
  "#c9b8e1",
  "#53718d",
  "#202a44",
  "#132b59",
  "#2c81d4",
  "#afd8eb",
  "#6de4cf",
  "#043b34",
  "#545e45",
  "#f2c649",
  "#cfa32e",
  "#be7b17",
  "#ea8510",
  "#996515",
  "#493327",
  "#c19a6b",
  "#cbbba5",
  "#ffffff",
  "#c7c8ca",
  "#4a4855",
  "#000000",
  "#5e2a30",
  "#9f0317",
  "#f4c2c2",
  "#9e7070",
  "#f0938a",
  "#2d2d2d",
] as const;

export const titleColorKeys = [
  "default",
  "purple",
  "lilac",
  "aero",
  "blue navy",
  "french blue",
  "sky blue",
  "aquamarine",
  "emerald",
  "green army",
  "yellow",
  "mustard",
  "orange",
  "windsor tan",
  "chocolate",
  "camel",
  "beige",
  "white",
  "light grey",
  "dark grey",
  "black",
  "burgundy",
  "red",
  "baby pink",
  "old pink",
  "jean",
  "salmon",
  "worn black",
] as const;
